- hosts: vagrants
  user: vagrant
  become: yes
  tasks:
  - name: enable epel
    replace:
      dest: /etc/yum.repos.d/epel.repo
      regexp: "enabled *= *1"
      replace: "enabled=0"

  - name: install redis
    yum: name=redis state=present enablerepo=epel

  - name: install redis
    lineinfile:
      path: /etc/redis.conf
      state: present
      #ç½®æ›
      backrefs: yes
      backup: yes
      regexp: "^bind 127.0.0.1$"
      line: "bind 0.0.0.0"

  - name: start redis
    service: name=redis state=started
